version: "3.7"

services:
  playground:
    build:
      context: .
      dockerfile: playground.Dockerfile
    entrypoint: bash -c "while true; do sleep 10; done"
    networks:
      - resec-demo
    dns:
      - 172.16.238.10
      - 172.16.238.11
      - 172.16.238.12

  consul-agent-1: &consul-agent
    image: consul:latest
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0 -dns-port 53"
    environment:
      - CONSUL_ALLOW_PRIVILEGED_PORTS=
    networks:
      - resec-demo

  consul-agent-2:
    <<: *consul-agent

  consul-agent-3:
    <<: *consul-agent

  consul-server-1: &consul-server
    <<: *consul-agent
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0 -dns-port 53 --recursor 127.0.0.11"
    networks:
      resec-demo:
        ipv4_address: 172.16.238.12

  consul-server-2:
    <<: *consul-server
    networks:
      resec-demo:
        ipv4_address: 172.16.238.11

  consul-server-bootstrap:
    <<: *consul-agent
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0 -dns-port 53 --recursor 127.0.0.11"
    networks:
      resec-demo:
        ipv4_address: 172.16.238.10

  consul-resec-1:
    <<: *consul-agent
    hostname: "consul-resec-1"

  redis-resec-1: &redis
    image: redis:alpine
    hostname: "redis-resec-1"
    networks:
      - resec-demo

  resec-1: &resec
    image: seatgeek/resec
    hostname: "resec"
    networks:
      - resec-demo
    environment:
      REDIS_ADDR: redis-resec-1:6379
      CONSUL_HTTP_ADDR: http://consul-resec-1:8500
    depends_on:
      - consul-resec-1
      - redis-resec-1

  consul-resec-2:
    <<: *consul-agent
    hostname: "consul-resec-2"
  redis-resec-2:
    <<: *redis
    hostname: "redis-resec-2"
  resec-2:
    <<: *resec
    environment:
      REDIS_ADDR: redis-resec-2:6379
      CONSUL_HTTP_ADDR: http://consul-resec-2:8500
    depends_on:
      - consul-resec-2
      - redis-resec-2

  consul-resec-3:
    <<: *consul-agent
    hostname: "consul-resec-3"
  redis-resec-3:
    <<: *redis
    hostname: "redis-resec-3"
  resec-3:
    <<: *resec
    environment:
      REDIS_ADDR: redis-resec-3:6379
      CONSUL_HTTP_ADDR: http://consul-resec-3:8500
    depends_on:
      - consul-resec-3
      - redis-resec-3

networks:
  resec-demo:
    ipam:
      config:
        - subnet: "172.16.238.0/24"
